### ISSUE TITLE
device_ids 

### ISSUE THREAD

**Issue by ckcraig01** [kjunelee/MetaOptNet#5]
Thanks for the quick reply for the previous issue, you may close it.

Another issue is the device_ids seem to be hardcoded, I wonder if my observation is correct.

In train.py line 45:
network = torch.nn.DataParallel(network, device_ids=[0, 1, 2, 3])

 python train.py --gpu 0 --save-path "./experiments/miniImageNet_MetaOptNet_SVM" --train-shot 15 --head SVM --network ResNet --dataset miniImageNet --eps 0.1

Traceback (most recent call last):
  File "train.py", line 164, in <module>
    (embedding_net, cls_head) = get_model(opt)
  File "train.py", line 45, in get_model
    network = torch.nn.DataParallel(network, device_ids=[0, 1, 2, 3])
  File "/home/xxx/anaconda3/envs/metaopnet/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 102, in __init__
    _check_balance(self.device_ids)
  File "/home/xxx/anaconda3/envs/metaopnet/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 17, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/xxx/anaconda3/envs/metaopnet/lib/python2.7/site-packages/torch/cuda/__init__.py", line 292, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

**Comment by ckcraig01** [comment]
test in another device

**Comment by ckcraig01** [comment]
Thanks, my point here is that whether it is ok to set
network = torch.nn.DataParallel(network, device_ids=[0, 1, 2, 3]) for using partial gpus as
--gpu 0, --gpu 0,1, --gpu 0,1,2. If it is okay. Then it shall be no problem.

**Comment by kjunelee** [comment]
If you want to set --gpu 0,1
then you need to set
network = torch.nn.DataParallel(network, device_ids=[0, 1])
